export const PROJECTS = [
  {
    id: 1,
    title: 'Gerai Pintar — Mini ATM Feature Integration',
    type: 'Professional',
    role: 'Mobile Developer',
    tech: ['Flutter', 'Java', 'EMV Integration'],
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
    summary: 'Enhanced the Gerai Pintar mobile app by integrating Mini ATM functionality via EDC hardware — enabling card-based transactions (balance inquiry, withdrawal, transfer) with real-time EMV processing.',
    highlights: ['Bridged Feitian native Java EDC SDK into Flutter via platform & event channels','Implemented EMV card processing: chip, magnetic stripe, NFC (PAN, ICC, Track 2)','Applied AES encryption into transaction request flow per technical specifications','Developed balance inquiry, withdrawal, transfer, and history modules with REST API','Applied Cubit state management to isolate transaction lifecycle and sensitive data'],
    impact: ['Full Mini ATM functionality without a separate system','Reduced transaction latency via background geolocation optimization','Secure handling of sensitive transaction data in production'],
  },
  {
    id: 2,
    title: 'Warung Komunitas — Marketplace Web Application',
    type: 'Professional',
    role: 'Frontend Developer (Flutter Web)',
    tech: ['Flutter Web', 'Hive'],
    image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600&q=80',
    summary: 'A Flutter-based web marketplace for closed community environments — members browse products, access promotions, complete purchases, and manage transaction history.',
    highlights: ['Architected frontend using MVVM clean architecture with Cubit state management','Implemented responsive UI for desktop, tablet, and mobile','Configuration-driven theming via JSON runtime settings (no hardcoded assets)','Integrated Hive local storage for persistent cart management across sessions','Implemented URL-based routing with partial deep linking for promotional pages'],
    impact: ['Runtime branding flexibility without requiring rebuilds','Consistent cross-device experience with adaptive UI','Increased reliability and session persistence reducing transaction drop-offs'],
  },
  {
    id: 3,
    title: 'IBS Branchless Online Mobile Application',
    type: 'Professional',
    role: 'Mobile Developer',
    tech: ['Flutter'],
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=80',
    summary: 'A real-time Android app enabling bank officers to conduct on-site customer transactions, seamlessly integrated with the core banking system to eliminate branch reprocessing.',
    highlights: ['Redesigned entire UI: login, dashboard, and 9 operational modules in one APK','Built deposit (setoran) & installment (angsuran) transaction features end-to-end','Resolved printing incompatibility on Topwise mobile POS devices','Implemented QR-based account scanning to reduce manual entry errors'],
    impact: ['Modernized UX across the full live field banking application','Consistent receipt printing across all transaction modules','Minimized human error through QR-based account validation'],
  },
  {
    id: 4,
    title: 'ToDoList Mini App — Task Management Application',
    type: 'Personal Project',
    role: 'Full-Stack Mobile Developer',
    tech: ['Flutter', 'Laravel', 'REST API', 'MySQL', 'Hive'],
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=600&q=80',
    summary: 'A mobile ToDoList app built with Flutter and Laravel (MVVM, online-first caching). Features secure auth, task CRUD with filters, a dynamic calendar view, and Hive local caching.',
    highlights: ['MVVM architecture separating logic, view, and data layers','Laravel REST API backend with JWT authentication and MySQL','Hive caching to store data locally, reducing redundant API calls','Material 3 minimalist UI with gesture-based navigation and smooth animations'],
    impact: ['Seamless task management with offline-capable local caching','Improved load time with manual cache control for privacy'],
    githubUrl: 'https://github.com/aulianurulf',
  },
  {
    id: 5,
    title: 'Gatevent — Event Management System',
    type: 'Group Project',
    role: 'System Analyst & Back End Developer',
    tech: ['Laravel', 'MySQL'],
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80',
    summary: 'An event management system for Polban featuring a CSP-based scheduling engine that generates conflict-free agendas for competitions — reducing scheduling time from 3 days to under 1 minute.',
    highlights: ['Implemented CSP scheduling engine from scratch without external libraries','Generated 3 unique conflict-free schedules for 20+ categories tested with 1,000+ entries','Built constraint propagation and backtracking with heuristics','Added conflict-detection with clear failure messages for organizer editing'],
    impact: ['Scheduling time reduced from 3 days to under 1 minute','3 alternative conflict-free schedules generated simultaneously','Real-world tested with up to 1,000 entries of competition data'],
  },
  {
    id: 6,
    title: 'Mobile Banking — Laku Pandai Bank NTB Syariah',
    type: 'Group Project',
    role: 'Mobile Developer Intern',
    tech: ['Kotlin', 'Java', 'Android Studio', 'Laravel', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=600&q=80',
    summary: 'A mobile banking app for Bank NTB Syariah agents enabling fund transfers, interbank transfers, cash withdrawals, and deposits outside branch offices.',
    highlights: ['75+ dynamic, database-driven screens built','100+ services integrated connecting transaction flows with data models','Data-driven architecture minimizing hardcoding for flexible updates','Mobile authentication and debugging of API mismatches with backend teams','UAT participation with the partner bank refining transaction flows'],
    impact: ['Banking services accessible outside branch offices for wider communities','Scalable architecture enabling UI updates without full redeployment'],
  },
  {
    id: 7,
    title: 'QuickFy — Personal Data Autofill with Cryptography',
    type: 'Group Project',
    role: 'Fullstack Developer',
    tech: ['Laravel', 'Flutter', 'Firebase', 'MySQL'],
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=600&q=80',
    summary: 'A mobile app that securely stores user data and enables autofill across partner applications — inspired by SingPass. Won 1st place in Product Profile Design at KMIPN VI.',
    highlights: ['Developed entire API layer in Laravel for personal, education, employment, and family data','Authentication and authorization flows with history-tracking module','Firebase Cloud Messaging for real-time approval notifications','4-step autofill: save once → login on partner app → approve → pre-filled form'],
    impact: ['🏆 1st Place — Product Profile Design at KMIPN VI (National)','Pre-filled dozens of personal data fields in just 4 user steps'],
    isAward: true,
  },
  {
    id: 8,
    title: 'CV Creative — Web Application',
    type: 'Group Project',
    role: 'FullStack Developer',
    tech: ['Laravel', 'Bootstrap'],
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=600&q=80',
    summary: 'A web application that generates professional CVs from structured user input using customizable templates — built as an academic Laravel learning project.',
    highlights: ['Modules for personal data, skills, and supporting documents','Template-based CV generation engine producing downloadable CVs','Responsive frontend with clean, intuitive interface across devices'],
    impact: ['Users create consistent professional CVs without manual formatting'],
  },
  {
    id: 9,
    title: 'Scientific Calculator Project',
    type: 'Group Project',
    role: 'Desktop Developer',
    tech: ['C'],
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80',
    summary: 'A scientific calculator built in C using linked list and tree data structures to evaluate mathematical expressions with proper operator precedence.',
    highlights: ['Parsing system converting infix input into a tree representation','Linked list for token management and traversal order','Implemented exponent, root, and trigonometric functions as specific node types'],
    impact: ['Accurately evaluates complex nested mathematical expressions','Validates user input efficiently through tree-based recursive evaluation'],
  },
]